# Generated by Django 4.2.9 on 2024-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_task',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
