# Generated by Django 4.2.9 on 2024-01-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_purchaseactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseactivity',
            name='grandtotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
