# Generated by Django 4.2 on 2024-01-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_purchaseactivity_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseactivity',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasepackage', to='myapp.package'),
        ),
    ]
